version: '3'

services:
  test_postgres:
    build: .
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes: 
      - db1:/var/lib/postgresql/data

  postgres_2:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes: 
      - db2:/var/lib/postgresql/data

volumes:
  db1:
  db2:
